<? php
echo "<!DOCTYPE html>";
echo "";
echo "<html>";
echo "";
echo "<head>";
echo "";
echo "<meta charset="utf-8">";
echo "<meta name="viewport" content="width=device-width, initial-scale=1">";
echo "<title>The Royal Brothers</title>";
echo "";
echo "<link rel="stylesheet" href="style.css"/>";
echo "<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">";
echo "<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">";
echo "</head>";
echo "";
echo "<body>";
echo "";
echo "<?php{";
echo "echo "Hello";";
echo "$servername = "localhost";";
echo "$username = "id6274026_bikes";";
echo "$password = "royalbrothers";";
echo "$dbname = "id6274026_bikes";";
echo "";
echo "$html = new DOMDocument();";
echo "$html->loadHTMLFile("get.php");";
echo "$html->getElementById("triall")->nodeValue = "Hello There";";
echo "$html->saveHTMLFile("bikes.html");";
echo "$str="hello";";
echo "$conn = new mysqli($servername, $username, $password, $dbname);";
echo "";
echo "if ($conn->connect_error) {";
echo "die("Connection failed: " . $conn->connect_error);";
echo "}";
echo "";
echo "$sql="SELECT BikeNos,BikeID FROM Bikes"";
echo "?>";
echo "";
echo "<div  id="refno" style="top:-50px">";
echo "<p>Refer Friends  9900336655 / 9955664422</p>";
echo "</div>";
echo "";
echo "<div id="navbar">";
echo "<img src="img/royalbrothers_logo.png">";
echo "<span class="RBLogoText">";
echo "Royal<br>Brothers";
echo "</span>";
echo "<a href="#">Contact us</a>";
echo "<a href="addbike.html">Add Bikes</a>";
echo "<a href="bikes.html" method="POST" action="get.php">Bikes</a>";
echo "<a href="index.html" style="align-right">Home</a>";
echo "</div>";
echo "<br/>";
echo "<div class="row" style="margin-left:10%;margin-right:10%; width:100%">";
echo "<div class="card">";
echo "<div class="container">";
echo "<center><h4><b>Harley Davidson</b></h4></center>";
echo "<img src="img/royalbrothers_logo.png" alt="Avatar" style="width:100%">";
echo "<center><p style="margin-bottom:0;">Not Available</p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>01:30PM          08:30PM</b></pre></p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>15Jun18    TO    17Jun18</b></pre></p></center>";
echo "";
echo "</div>";
echo "<div style="background-color:#fecc00; width:100%; padding:5px;">";
echo "<p class="pos" style="position:relative; float:left;"><b>Rs.5500/-</b><br/><span style="font-size:0.6em">(inclusive of all taxes)</span></p>";
echo "<a href="#"><h5 class="pos" style="float:right; font-weight:bold; background-color:white; margin-top:0.5em; padding-bottom:5px; padding-top:5px; color:black;">BOOK</h5></a>";
echo "</div>";
echo "</div>";
echo "<div class="card">";
echo "<div class="container">";
echo "<center><h4><b>Apache</b></h4></center>";
echo "<img src="img/royalbrothers_logo.png" alt="Avatar" style="width:100%">";
echo "<center><p style="margin-bottom:0;">Not Available</p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>01:30PM          08:30PM</b></pre></p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>15Jun18    TO    17Jun18</b></pre></p></center>";
echo "";
echo "</div>";
echo "<div style="background-color:#fecc00; width:100%; padding:5px;">";
echo "<p class="pos" style="position:relative; float:left;"><b>Rs.5500/-</b><br/><span style="font-size:0.6em">(inclusive of all taxes)</span></p>";
echo "<a href="#"><h5 class="pos" style="float:right; font-weight:bold; background-color:white; margin-top:0.5em; padding-bottom:5px; padding-top:5px; color:black;">BOOK</h5></a>";
echo "</div>";
echo "</div>";
echo "<div class="card">";
echo "<div class="container">";
echo "<center><h4><b>Yamaha</b></h4></center>";
echo "<img src="img/royalbrothers_logo.png" alt="Avatar" style="width:100%">";
echo "<center><p style="margin-bottom:0;">Not Available</p></center>";
echo "<center><p id="tirall" style="margin-bottom:0;"><pre><b>01:30PM          08:30PM</b></pre></p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>15Jun18    TO    17Jun18</b></pre></p></center>";
echo "";
echo "</div>";
echo "<div style="background-color:#fecc00; width:100%; padding:5px;">";
echo "<p class="pos" style="position:relative; float:left;"><b>Rs.5500/-</b><br/><span style="font-size:0.6em">(inclusive of all taxes)</span></p>";
echo "<a href="#"><h5 class="pos" style="float:right; font-weight:bold; background-color:white; margin-top:0.5em; padding-bottom:5px; padding-top:5px; color:black;">BOOK</h5></a>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class="row" style="margin-left:10%;margin-right:10%; width:100%">";
echo "<div class="card">";
echo "<div class="container">";
echo "<center><h4><b>Activa</b></h4></center>";
echo "<img src="img/royalbrothers_logo.png" alt="Avatar" style="width:100%">";
echo "<center><p style="margin-bottom:0;">Not Available</p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>01:30PM          08:30PM</b></pre></p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>15Jun18    TO    17Jun18</b></pre></p></center>";
echo "";
echo "</div>";
echo "<div style="background-color:#fecc00; width:100%; padding:5px;">";
echo "<p class="pos" style="position:relative; float:left;"><b>Rs.5500/-</b><br/><span style="font-size:0.6em">(inclusive of all taxes)</span></p>";
echo "<a href="#"><h5 class="pos" style="float:right; font-weight:bold; background-color:white; margin-top:0.5em; padding-bottom:5px; padding-top:5px; color:black;">BOOK</h5></a>";
echo "</div>";
echo "</div>";
echo "<div class="card">";
echo "<div class="container">";
echo "<center><h4><b>RoyalEnfield</b></h4></center>";
echo "<img src="img/royalbrothers_logo.png" alt="Avatar" style="width:100%">";
echo "<center><p style="margin-bottom:0;">Not Available</p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>01:30PM          08:30PM</b></pre></p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>15Jun18    TO    17Jun18</b></pre></p></center>";
echo "";
echo "</div>";
echo "<div style="background-color:#fecc00; width:100%; padding:5px;">";
echo "<p class="pos" style="position:relative; float:left;"><b>Rs.5500/-</b><br/><span style="font-size:0.6em">(inclusive of all taxes)</span></p>";
echo "<a href="#"><h5 class="pos" style="float:right; font-weight:bold; background-color:white; margin-top:0.5em; padding-bottom:5px; padding-top:5px; color:black;">BOOK</h5></a>";
echo "</div>";
echo "</div>";
echo "<div class="card">";
echo "<div class="container">";
echo "<center><h4><b>Duke</b></h4></center>";
echo "<img src="img/royalbrothers_logo.png" alt="Avatar" style="width:100%">";
echo "<center><p style="margin-bottom:0;">Not Available</p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>01:30PM          08:30PM</b></pre></p></center>";
echo "<center><p style="margin-bottom:0;"><pre><b>15Jun18    TO    17Jun18</b></pre></p></center>";
echo "";
echo "</div>";
echo "<div style="background-color:#fecc00; width:100%; padding:5px;">";
echo "<p class="pos" style="position:relative; float:left;"><b>Rs.5500/-</b><br/><span style="font-size:0.6em">(inclusive of all taxes)</span></p>";
echo "<a href="#"><h5 class="pos" style="float:right; font-weight:bold; background-color:white; margin-top:0.5em; padding-bottom:5px; padding-top:5px; color:black;">BOOK</h5></a>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "";
echo "";
echo "<div id="pagebase" style="position:relative; padding-left:10%; padding-right:10%; background-color:#363636;">";
echo "<div class="row">";
echo "<div class="colD" style="width:35%">";
echo "<div class="row">";
echo "<div style="float:left; padding:10px;"><img src="img/royalbrothers_logo.png" style="padding:10px;"></image></div>";
echo "<div style="width:50%; float:left;">";
echo "<h3 style="font-weight:bold; font-size:300%; padding:5px; color:white;"><span style="color:#fecc00;">Royal</span> Brothers</h3>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class="colD" style="width">";
echo "<ul>";
echo "<li><h5 style="color:white; font-weight:bold;">COMPANY</h5></li>";
echo "<li><a href=#>FAQ"s</a></li>";
echo "<li><a href=#>Privacy Policy</a></li>";
echo "<li><a href=#>Terms and Conditions</a></li>";
echo "<ul>";
echo "</div>";
echo "";
echo "<div class="colD">";
echo "<ul>";
echo "<br/>";
echo "<li><a href=#>Tariff</a></li>";
echo "<li><a href=#>Partner with us</a></li>";
echo "<li><a href=#>Reach Us</a></li>";
echo "<li><a href=#>About Us</a></li>";
echo "<li><a href=#>Site Map</a></li>";
echo "<ul>";
echo "</div>";
echo "";
echo "<div class="colD">";
echo "<ul>";
echo "<li><h5 style="color:white; font-weight:bold;">Follow</h5></li>";
echo "<li><a href=#>Facebook</a></li>";
echo "<li><a href=#>Twitter</a></li>";
echo "<li><a href=#>Instagram</a></li>";
echo "<li><a href=#>Linkedin</a></li>";
echo "<ul>";
echo "</div>";
echo "</div>";
echo "";
echo "<div>";
echo "<p style="text-align:center; color:grey; margin-bottom:0;">©Copyright 2017 Royalbison AutoRentals India Private Ltd.All rights reserved.</p>";
echo "</div>";
echo "</div>";
echo "";
echo "<script>";
echo "//---------------navbar sticky-------------------";
echo "window.onscroll = function() {myFunction()};";
echo "var navbar = document.getElementById("navbar");";
echo "var sticky = navbar.offsetTop;";
echo "function myFunction() {";
echo "if (window.pageYOffset >= sticky) {";
echo "navbar.classList.add("sticky")";
echo "} else {";
echo "navbar.classList.remove("sticky");";
echo "}";
echo "}";
echo "</script>";
echo "</body>";
echo "";
echo "</html>";
echo "";
echo "";
?>